### ISSUE TITLE
cucumberOpts.profile doesn't pick up profile

### ISSUE THREAD

**Issue by si-mikey** [webdriverio/wdio-cucumber-framework#35] opened 2016-09-19 21:03 UTC
I've got 
```js
wdio wdio.conf.js --cucumberOpts.profile 'critical'
```
And in cucumber.js file got 
```js
module.exports = {
  'default': '--format rerun:@rerun.txt',
  'critical': '--tags @critical'
}
```
And various scenarios tagged @wip, @high and 1 tagged as @critical 
when I run the wdio running command all the tests run and not that specific profile. Anyone know If im doing something wrong?

**Comment by christian-bromann** [comment] 2016-09-19 21:04
duplicate of #9

**Closed by christian-bromann** 2016-09-19 21:04 UTC
