### ISSUE TITLE
Stacktrace when using Background in cucumber

### ISSUE THREAD

**Issue by jonsmithers** [webdriverio/wdio-cucumber-framework#114] opened 2018-04-06 20:19 UTC
```
․ERROR: Cannot read property 'type' of undefined
chrome
Type    at CucumberReporter.getUniqueIdentifier (/path/to/project/node_modules/wdio-cucumber-framework/build/reporter.js:304:24)
    at CucumberReporter.handleBeforeStep (/path/to/project/node_modules/wdio-cucumber-framework/build/reporter.js:103:27)
    at CucumberEventListener.emit (events.js:180:13)
    at CucumberEventListener.emit (domain.js:421:20)
    at CucumberEventListener.onTestStepStarted (/path/to/project/node_modules/wdio-cucumber-framework/build/cucumberEventListener.js:159:18)
    at EventEmitter.emit (events.js:185:15)
    at EventEmitter.emit (domain.js:421:20)
    at TestCaseRunner.emit (/path/to/project/node_modules/cucumber/lib/runtime/test_case_runner.js:94:29)
    at TestCaseRunner.<anonymous> (/path/to/project/node_modules/cucumber/lib/runtime/test_case_runner.js:191:14)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/path/to/project/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/path/to/project/node_modules/bluebird/js/release/generators.js:97:49)
    at TestCaseRunner.<anonymous> (/path/to/project/node_modules/bluebird/js/release/generators.js:201:15)
    at TestCaseRunner.aroundTestStep (/path/to/project/node_modules/cucumber/lib/runtime/test_case_runner.js:210:22)
    at /path/to/project/node_modules/cucumber/lib/runtime/test_case_runner.js:314:26
    at Generator.next (<anonymous>)
```

Feature:

```gherkin
Feature: thing with background
	Background:
		Given admin is logged in

	Scenario: do stuff
		Given user is on some page
		Then I win
```

I took some screencaps will debugging which I think might point to the source of the problem. It tries to fetch index 2 (`testStepStartedEvent.index`) from an array of length 2 `scenario.steps`, so `scenario.steps[testStepStartedEvent.index]` obviously returns `undefined`. I think this happens because it assumes all the steps are inside the scenario and doesn't account for steps coming from the feature's background. 

Instead of

```javascript
scenario.steps[testStepStartedEvent.index]
```

It should probably be
```javascript
[...feature.children.background.steps, ...scenario.steps][testStepStartedEvent.index]
```

![screen shot 2018-04-06 at 4 00 49 pm](https://user-images.githubusercontent.com/2660313/38442027-d34b8d8a-39b4-11e8-8504-64a2b5b049cd.png)
![screen shot 2018-04-06 at 4 02 57 pm](https://user-images.githubusercontent.com/2660313/38442038-dc1efe92-39b4-11e8-91f7-23d117f42ce8.png)
![screen shot 2018-04-06 at 4 03 46 pm](https://user-images.githubusercontent.com/2660313/38442042-de39a0f6-39b4-11e8-94e7-5b9258e5fe1d.png)

**Comment by BorisOsipov** [comment] 2018-04-07 05:57
duplicate of https://github.com/webdriverio/wdio-cucumber-framework/issues/112

**Closed by BorisOsipov** 2018-04-07 05:57 UTC
