### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by cnatis** [webdriverio/wdio-cucumber-framework#76] opened 2017-08-30 17:28 UTC
Trying to run the tests using `npm run test` fails

```
\Desktop\Projects\wdio-cucumber-framework
λ npm run test

> wdio-cucumber-framework@1.0.1 test C:\Users\cnatis.OCULUS\Desktop\Projects\wdio-cucumber-framework
> run-s eslint test:unit build test:postadapter


> wdio-cucumber-framework@1.0.1 eslint C:\Users\cnatis.OCULUS\Desktop\Projects\wdio-cucumber-framework
> eslint ./lib test/


> wdio-cucumber-framework@1.0.1 test:unit C:\Users\cnatis.OCULUS\Desktop\Projects\wdio-cucumber-framework
> mocha --compilers js:babel-core/register './test/!(adapter.spec).js'

.js' was unexpected at this time.

\Desktop\Projects\wdio-cucumber-framework {git}{hg}
{lamb}   "wdio-cucumber-framework\node_modules\.bin\\node.exe"  "wdio-cucumber-framework\node_modules\.bin\\..\mocha\bin\mocha" --compilers js:babel-core/register './test/!(adapter.spec).js'
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! wdio-cucumber-framework@1.0.1 test:unit: `mocha --compilers js:babel-core/register './test/!(adapter.spec).js'`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the wdio-cucumber-framework@1.0.1 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     AppData\Roaming\npm-cache\_logs\2017-08-30T17_24_10_902Z-debug.log
ERROR: "test:unit" exited with 255.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wdio-cucumber-framework@1.0.1 test: `run-s eslint test:unit build test:postadapter`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wdio-cucumber-framework@1.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     

AppData\Roaming\npm-cache\_logs\2017-08-30T17_24_10_972Z-debug.log
```

[2017-08-30T17_24_10_902Z-debug.txt](https://github.com/webdriverio/wdio-cucumber-framework/files/1264488/2017-08-30T17_24_10_902Z-debug.txt)
[2017-08-30T17_24_10_972Z-debug.txt](https://github.com/webdriverio/wdio-cucumber-framework/files/1264490/2017-08-30T17_24_10_972Z-debug.txt)

**Comment by christian-bromann** [comment] 2017-08-30 17:37
Tried with a fresh install and wasn't able to reproduce this. It looks like a windows issue. As much as I would like to have this fix it doesn't bother me. I also don't use windows. I will close this issue because I am sure it has nothing to do with the setup of the test. I is probably some dependency issue.

**Closed by christian-bromann** 2017-08-30 17:37 UTC
