### ISSUE TITLE
WDIO test runner ignores all tests if multiple tags are specified in cucumberOpts

### ISSUE THREAD

**Issue by prasanjitmohanty** [webdriverio/wdio-cucumber-framework#47] opened 2017-02-06 13:38 UTC
If I am specifying multiple tags  e.g - tags: ['@P1','@P2'],  in cucumberOpts the test runner ignores all tests without any error. I have test scenarios for both tags. It only works if only one tag or without any tag.

"webdriverio": ^4.6.2",
"wdio-cucumber-framework": "^0.2.5",

```
cucumberOpts: {
        require: [
        ],        // <string[]> (file/dir) require files before executing features
        backtrace: false,   // <boolean> show full backtrace for errors
        // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        dryRun: false,      // <boolean> invoke formatters without executing steps
        failFast: false,    // <boolean> abort the run on first failure
        format: ['pretty'], // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
        colors: true,       // <boolean> disable colors in formatter output
        snippets: false,     // <boolean> hide step definition snippets for pending steps
        source: true,       // <boolean> hide source uris
        profile: [],        // <string[]> (name) specify the profile to use
        strict: false,      // <boolean> fail if there are any undefined or pending steps
        tags: ['@P1','@P2'],           // <string[]> (expression) only execute the features or scenarios with tags matching the expression
        timeout: 120000,     // <number> timeout for step definitions
        ignoreUndefinedDefinitions: true, // <boolean> Enable this config to treat undefined definitions as warnings.
    }
```

**Comment by prasanjitmohanty** [comment] 2017-02-07 17:05
It is an issue with "cucumber": "~1.3.1" used which fails in case of multiple tags. The current version is 2.0.0 so my guess is doing a dependency upgrade will fix this for wdio-cucumber-framework.

**Comment by broder** [comment] 2017-03-08 13:56
I was struggling with this too and I think the issue is that old-style cucumber tags (e.g. in cucumber-js 1.3.1) are confusing (this is fixed with new-style cucumber tags: https://docs.cucumber.io/tag-expressions/#migrating-from-old-style-tags)

In your case:

- `tags: ['@P1','@P2']` would run scenarios tagged with `@P1` AND `@P2`
- `tags: ['@P1,@P2']` would run scenarios tagged with `@P1` OR `@P2` - I think this is the one you want

**Comment by christian-bromann** [comment] 2017-03-11 16:12
We don't support Cucumber v2 and I am not even sure if we ever will as it seems that we are not able to integrate WebdriverIO in a way we are with v1.x. Once v2 is finally released I will take a look again. Until then please use the solution suggested by @broder (thanks!).

**Closed by christian-bromann** 2017-03-11 16:12 UTC

**Comment by prasanjitmohanty** [comment] 2017-03-13 10:03
Please don't close the issue. As the suggested  approach is not working. Looks like wdio-cucumber-framework needs to handle this  before passing it to the cucumber

If tags passed as  `tags: ['@P1 OR @P2'], ` - It skips all tests
If tags passed as  `tags: '@P1 OR @P2', ` - ERROR: tagGroupStrings.map is not a function

**Comment by broder** [comment] 2017-03-13 10:05
You need to pass tags as `tags: ['@P1','@P2']` or `tags: ['@P1,@P2']`

**Comment by prasanjitmohanty** [comment] 2017-03-13 10:33
tags: ['@P1,@P2'] works. Thanks for the help
