### ISSUE TITLE
Usage of tagExpression opens browser instances for tests that are not included in the tagExpression

### ISSUE THREAD

**Issue by rgustavsson** [webdriverio/wdio-cucumber-framework#85] opened 2017-11-29 10:29 UTC
We have 10 feature files where 5 of them are tagged a '@smoke'.  
When we run all '@smoke' feature tests only those 5 features are executed but 10 browsers are opened and closed.

For example:

:thumbsdown: Test 1: Not tagged with '@smoke'. A browser instance is opened and then immediately closed.

:thumbsup: Test 2: Test is tagged with '@smoke'. A browser instance is opened, test executed and then the browser instance is closed.

:thumbsdown: Test 3: Not tagged with '@smoke'. A browser instance is opened and then immediately closed.

etc..

The problem with this is that is takes extra time to run all our tests just because non-tagged tests cause a browser open & close.

Using webdriverio 4.9.9 & wdio-cucumber-framework 1.0.2

**Comment by christian-bromann** [comment] 2017-11-29 10:38
Duplicate of webdriverio/webdriverio#1247

**Closed by christian-bromann** 2017-11-29 10:38 UTC
