### ISSUE TITLE
Errors out with cucumber.js 2.x

### ISSUE THREAD

**Issue by souptown** [webdriverio/wdio-cucumber-framework#42] opened 2016-11-30 05:12 UTC
Cucumber.SupportCode seems to be undefined. This is a problem for someone working through the examples, because the default install of cucumber.js is now 2.x.

```
[22:52:40]  COMMAND     POST     "/wd/hub/session"
[22:52:40]  DATA                {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"maxInstances":5,"browserName":"chrome","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.4.0","name":"webdriverio"}}}
[22:52:42]  INFO        SET SESSION ID ceb7807c-b201-46b9-b25e-e01c32ba4403
[22:52:42]  RESULT              {"applicationCacheEnabled":false,"rotatable":false,"mobileEmulationEnabled":false,"networkConnectionEnabled":false,"chrome":{"chromedriverVersion":"2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed)","userDataDir":"C:\\Users\\mmiller\\AppData\\Local\\Temp\\scoped_dir26084_13138"},"takesHeapSnapshot":true,"pageLoadStrategy":"normal","databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"version":"54.0.2840.99","platform":"XP","browserConnectionEnabled":false,"nativeEvents":true,"acceptSslCerts":true,"webdriver.remote.sessionid":"ceb7807c-b201-46b9-b25e-e01c32ba4403","locationContextEnabled":true,"webStorageEnabled":true,"browserName":"chrome","takesScreenshot":true,"javascriptEnabled":true,"cssSelectorsEnabled":true}
ERROR: Cannot read property 'StepDefinition' of undefined
chrome
Type    at new CucumberAdapter (C:\repositories\webdriverio-test\node_modules\wdio-cucumber-framework\build\adapter.js:227:55)
    at Object.callee$0$0$ (C:\repositories\webdriverio-test\node_modules\wdio-cucumber-framework\build\adapter.js:416:27)
    at tryCatch (C:\repositories\webdriverio-test\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\repositories\webdriverio-test\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\regenerator\runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\repositories\webdriverio-test\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\regenerator\runtime.js:105:21)
    at tryCatch (C:\repositories\webdriverio-test\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at invoke (C:\repositories\webdriverio-test\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\regenerator\runtime.js:146:20)
    at C:\repositories\webdriverio-test\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\regenerator\runtime.js:191:11
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (C:\repositories\webdriverio-test\node_modules\wdio-cucumber-framework\node_modules\core-js\library\modules\$.export.js:30:36)
    at callInvokeWithMethodAndArg (C:\repositories\webdriverio-test\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\regenerator\runtime.js:190:16)
    at AsyncIterator.enqueue (C:\repositories\webdriverio-test\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\regenerator\runtime.js:211:37)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\repositories\webdriverio-test\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\regenerator\runtime.js:105:21)
    at Object.runtime.async (C:\repositories\webdriverio-test\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\regenerator\runtime.js:228:12)
    at Object.callee$0$0 [as run] (C:\repositories\webdriverio-test\node_modules\wdio-cucumber-framework\build\adapter.js:413:32)
    at Runner._callee$ (C:\repositories\webdriverio-test\node_modules\webdriverio\build\lib\runner.js:228:55)
    at tryCatch (C:\repositories\webdriverio-test\node_modules\regenerator-runtime\runtime.js:63:40)
```

**Comment by christian-bromann** [comment] 2016-11-30 10:44
Duplicate of #41

**Closed by christian-bromann** 2016-11-30 10:44 UTC
